title: Wheel of Fortune Analysis
description: Analysis of the game show Wheel of Fortune
url: "https://chengeric155.github.io/Wheel-of-Fortune-Analysis/"

author:
  name: Eric Cheng

remote_theme: jekyll/minima

minima:
  social_links:
    github: chengeric155